### ISSUE TITLE
ImportError: compiled unit contain version 37 code (38 required)

### ISSUE THREAD

**Issue by ImageAnalyst** [StuartLab/MiNA#17]
Dear all, 
I install the last version of Fiji, Stuart lab and Biomedgroup and I tried Mina on 2 PC.
I  deleted the file in question: Fiji.app/jars/Lib/eztables/__init__$py.class and  other $py.class files in that folder.
But I always have the same issue.
Could you help me ?

Kind regards,

![image](https://user-images.githubusercontent.com/71371449/93302190-de7ef100-f7f9-11ea-819c-736e64cb5d15.png)

**Comment by RodoVJ** [comment]
Hello ImageAnalyst, 

MiNA has now been updated and a new version has been released with the latest commit of the "Master" branch of this repository. Please check it out and follow the Installation instructions of the README.

All the best

**Comment by ImageAnalyst** [comment]
Dear @RodoVJ ,
Thank you for your help
