### ISSUE TITLE
Error Message on MINA

### ISSUE THREAD

**Issue by hanan-92** [StuartLab/MiNA#26]
Hi 
On running the plugin ( MINA analyze morphology ) tool I received the following message : 

(3D [dev] 1.6.0-scijava-2-pre11-daily-experimental daily

C:\Users\SPECTRE\.ImageJ_3D_Viewer.props (The system cannot find the file specified)

**Comment by RodoVJ** [comment]
Hi,
Would you mind providing me with the version of MiNA you are using as well as your operating system, version of FIJI and the steps you take before the error message pops up?

Thank you

**Comment by hanan-92** [comment]
Hi
   I installed MiNA version 3.0 on Windows-10.
Thank you
