### ISSUE TITLE
Plugin crashing on updated fiji

### ISSUE THREAD

**Issue by Twisterdoc** [StuartLab/MiNA#28]
Updated FIJI today, and the plugin won't run
[ERROR] Traceback (most recent call last):
  File "Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py", line 20, in <module>
ImportError: compiled unit contains version 37 code (38 required)

**Comment by RodoVJ** [comment]
Hello,

MiNA has now been updated and a new version has been released with the latest commit of the "Master" branch of this repository. Please check it out and follow the Installation instructions of the README.

All the best
